
server: 
  port: 8083 
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka/
spring:
    application:
        name: APIGateWay
    cloud:
     gateway:
      routes:
        
        - id: DoctorModule
          uri: http://localhost:8091/
          predicates:
           Path= /api/v1/doctor/**
        - id: PatientModule
          uri: http://localhost:8090/
          predicates:
           Path= /api/v1/patient/**
        - id: UserModule
          uri: http://localhost:8080/
          predicates:
           Path= /api/v1/user/**